// Builds the code that runs inside the WebView and writes it to src/generated/runtime.js:
//   core:  @tryonit/core                     (loaded as the "@tryonit/core" module)
//   three: the three.js renderer             (loaded lazily, only for 3D products)
//   main:  bridge + @tryonit/web             (everything else, inlined)
// MediaPipe and three.js are not bundled: the page loads them lazily from a CDN through an
// import map, exactly like the web packages do.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { rolldown } from 'rolldown';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');
const packages = join(pkg, '..');
const THREE_RENDERER = '@tryonit/web-three-renderer';

const isExternal = (id) =>
  id === '@tryonit/core' ||
  id.startsWith('@mediapipe/') ||
  id === 'three' ||
  id.startsWith('three/') ||
  id === THREE_RENDERER;

const tryonitSources = {
  name: 'tryonit-sources',
  resolveId(source, importer) {
    if (!importer) return null; // entry modules are bundled, never external
    if (source === '@tryonit/web') return join(packages, 'web/src/index.ts');
    if (/renderers\/three\/three-renderer(\.ts)?$/.test(source))
      return { id: THREE_RENDERER, external: true };
    if (isExternal(source)) return { id: source, external: true };
    return null;
  },
};

async function bundle(input, external = true) {
  const build = await rolldown({
    input,
    plugins: external ? [tryonitSources] : [],
    logLevel: 'silent',
    platform: 'browser',
  });
  const { output } = await build.generate({ format: 'esm', minify: true, codeSplitting: false });
  await build.close();
  const chunks = output.filter((o) => o.type === 'chunk');
  if (chunks.length !== 1) throw new Error(`Expected one chunk for ${input}, got ${chunks.length}`);
  return chunks[0].code;
}

const readVersion = (path) => JSON.parse(readFileSync(path, 'utf8')).version;

const runtime = {
  core: await bundle(join(packages, 'core/src/index.ts'), false),
  three: await bundle(join(packages, 'web/src/renderers/three/three-renderer.ts')),
  main: await bundle(join(pkg, 'runtime/bridge.ts')),
  css: readFileSync(join(packages, 'web/src/mount/mount.css'), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' '),
  versions: {
    tryonit: readVersion(join(pkg, 'package.json')),
    mediapipe: readVersion(join(packages, 'web/node_modules/@mediapipe/tasks-vision/package.json')),
    three: readVersion(join(packages, 'web/node_modules/three/package.json')),
  },
};

const out = join(pkg, 'src/generated/runtime.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/build-runtime.mjs. Do not edit.\nexport const RUNTIME = ${JSON.stringify(runtime)};\n`,
);
const kb = (s) => `${(s.length / 1024).toFixed(1)} KB`;
console.log(
  `runtime: core ${kb(runtime.core)}, main ${kb(runtime.main)}, three ${kb(runtime.three)}, css ${kb(runtime.css)}`,
);
console.log(`versions: ${JSON.stringify(runtime.versions)}`);
